version: '3.4'

services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: on-failure
        container_name: sql-server
        hostname: sqlserver
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=System123
        healthcheck:
            test: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P System123 -Q "select 1"
            interval: 30s
            timeout: 30s
            retries: 3
        ports:
            - "1434:1433"
        volumes:
            - /c/mssql:/ver/opt/mssql/data

    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        restart: on-failure
        container_name: zoo-keeper
        hostname: zookeeper
        ports:
            - 2121:2121
        volumes:
            - /c/kafka/zk_logs:/var/lib/zookeeper/log
            - /c/kafka/zk_data:/var/lib/zookeeper/data
        environment:
            ZOOKEEPER_CLIENT_PORT: 2121
            ZOOKEEPER_TICK_TIME: 2000

    broker-1:
        image: confluentinc/cp-kafka:latest
        restart: on-failure
        container_name: broker-1
        hostname: broker-1
        depends_on:
            - zookeeper
        extra_hosts:
            - 'moby:127.0.0.1'
            - 'localhost: 127.0.0.1'
        ports:
            - 9091:9091
            - 9092:9092
        volumes:
            - /c/kafka/kf_data:/var/lib/kafka/data
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2121'
            KAFKA_LISTENERS: 'PLAINTEXT://broker-1:9092,INTERNAL://broker-1:9091'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT'
            KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
            KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092,INTERNAL://broker-1:9091'
            KAFKA_DELETE_TOPIC_ENABLE: 'true'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_NUM_PARTITIONS: 2
            KAFKA_AUTO_CREATE_TOPICS_ENABLED: ' false'

    redis:
        image: redis:5.0-rc-alpine3.8
        container_name: redis
        hostname: redis
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANES=FLUSHDB,FLUSHALL
        ports:
            - 6379:6379
        volumes:
            - C:\containers\redis:/bitnami/redis

    kafdrop:
        image: obsidiandynamics/kafdrop:3.27.0
        restart: on-failure
        container_name: kafdrop
        hostname: kafdrop
        depends_on:
            - broker-1
        environment:
            - KAFKA_BROKERCONNECT=broker-1:9091
        ports:
            - 9000:9000